services:
  - type: web
    name: ochacare-kenya
    plan: free
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DIST_DIR
        value: .next
